#!/usr/bin/env python3
"""Generate TypedDict stubs from scripts/resource_type_spec.json."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SPEC_PATH = ROOT / "scripts" / "resource_type_spec.json"
OUTPUT_PATH = ROOT / "src" / "clicksign" / "types" / "resources.py"

TYPE_MAP = {
    "str": "str",
    "bool": "bool",
    "int": "int",
    "dict": "dict[str, Any]",
    "list_str": "list[str]",
}


def _typed_dict(name: str, fields: dict[str, str]) -> str:
    if not fields:
        return f"class {name}(TypedDict):\n    pass\n"
    lines = [f"class {name}(TypedDict, total=False):"]
    for field_name, field_type in fields.items():
        py_type = TYPE_MAP.get(field_type, "Any")
        lines.append(f"    {field_name}: {py_type}")
    return "\n".join(lines) + "\n"


def main() -> None:
    spec = json.loads(SPEC_PATH.read_text(encoding="utf-8"))
    blocks: list[str] = [
        '"""Typed resource params — generated by scripts/generate_resource_types.py."""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Any, TypedDict",
        "",
    ]

    for resource_name, resource_spec in spec["resources"].items():
        attrs = resource_spec.get("attributes", {})
        blocks.append(_typed_dict(f"{resource_name}Attributes", attrs))
        blocks.append(_typed_dict(f"{resource_name}CreateParams", resource_spec.get("create", {})))
        blocks.append(_typed_dict(f"{resource_name}UpdateParams", resource_spec.get("update", {})))
        blocks.append(_typed_dict(f"{resource_name}FilterParams", resource_spec.get("filter", {})))

    OUTPUT_PATH.write_text("\n".join(blocks).rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
